<?php


namespace Farm;


class Cat extends Felime
{
    protected $breed;
   public function __construct($name, $animalType, $animalWeight, $foodEaten, $livingRegion,$breed)
   {
       parent::__construct($name, $animalType, $animalWeight, $foodEaten, $livingRegion);
       $this->breed=$breed;
   }

    public function makeSound()
    {
        return "Mayyyyy".PHP_EOL;
    }

    public function eat(Food $food)
    {
        parent::eat($food); // TODO: Change the autogenerated stub
    }
    public function __toString()//{AnimalType} [{AnimalName}, {CatBreed}, {AnimalWeight}, {AnimalLivingRegion}, {FoodEaten}]
    {
        return $this->animalType ."[".$this->name." ,".$this->breed." ,".$this->animalWeight." ,".$this->livingRegion." ,".$this->foodEaten."]";
    }
}