<?php

namespace Farm;


class Felime extends Mammal
{
   public function __construct($name, $animalType, $animalWeight, $foodEaten, $livingRegion)
   {
       parent::__construct($name, $animalType, $animalWeight, $foodEaten, $livingRegion);
   }

    public function makeSound()
    {
        return "Felimeeeeeee";
    }

    public function eat(Food $food)
    {
        parent::eat($food); // TODO: Change the autogenerated stub
    }
}