<?php

namespace FamilyTree;
class GrandSons extends Sons
{
    public function getTimeLived()
    {
        return parent::getTimeLived(); // TODO: Change the autogenerated stub
    }

    public function getGenerationNum()
    {
       return 3;
    }

}