<?php

namespace FamilyTree;
class Sons extends Father
{ public function getTimeLived()
{
    return parent::getTimeLived(); // TODO: Change the autogenerated stub
}

    public function getGenerationNum()
    {
        return 2;
    }
}